# The version of the golangci-lint configuration format
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - goimports

linters:
  enable:
    - errcheck
    - govet        
    - staticcheck  
    - wrapcheck  
    - importas  
    - unused  
    - ineffassign  

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
