erDiagram
    CRYPTO_KEY_META {
        string id PK
        string key_pair_id FK
        string user_id FK
        datetime date_time_created
        string algorithm
        uint key_size
        string type
    }

    BLOB_META {
        string id PK
        string encryption_key_id FK
        string sign_key_id FK
        string user_id FK
        datetime date_time_created
        string name
        int size
        string type
    }

    CRYPTO_KEY_META ||--o| BLOB_META : "associated with"
