erDiagram
    CRYPTOGRAPHIC_KEY {
        string id PK
        string type
        datetime date_time_created
        string user_id FK
    }

    BLOB {
        string id PK
        datetime date_time_created
        string user_id FK
        string key_id FK
        string name
        int size
        string type
        string encryption_algorithm
        string hash_algorithm
    }

    CRYPTOGRAPHIC_KEY ||--o| BLOB : "associated with"
