blob_connector:
  connection_string: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
  container_name: "testblobs"

key_connector:
  connection_string: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
  container_name: "testblobs"

logger:
  log_level: "info"   # Possible values: info, debug, error, warning, critical
  log_type: "console"    # Possible values: console, file
  file_path: ""  # Required if log_type is 'file'

pkcs11:
  module_path: "/usr/lib/softhsm/libsofthsm2.so"
  so_pin: "123456"
  user_pin: "234567"
  slot_id: "0x0"