name: Workflow for pre-release packages

on:
  push:
    branches: [main]

jobs:
  pre-release-package-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go 1.23.x 🐹
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Grant execute permissions
        run: chmod +x *
        working-directory: ./scripts

      - name: Run Unit tests
        run: ./run-test.sh -u
        working-directory: ./scripts

      - name: Spin up external storage services
        run: |
          docker compose up -d postgres azure-blob-storage

      - name: Install apt dependencies for integration test
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl opensc softhsm libssl-dev libengine-pkcs11-openssl

      - name: Run Integration tests
        run: sudo ./run-test.sh -i
        working-directory: ./scripts

      - name: Shut down external storage services
        run: |
          docker compose down -v

      # Run static code analysis on source code
      # Run vulnerability scanner and generate SBOMs on third part dependencies
      # Create build artifacts, e.g.  Build docker image with pre-release tag for applications, scan docker image and push to container registry